# One CLI to format the code tree - https://github.com/numtide/treefmt
[formatter.nix]
includes = ["*.nix"]
command = "alejandra"

[formatter.shell]
includes = ["*.sh"]
command = "shfmt"
options = [
  "-i",
  "2", # indent 2
  "-s", # simplify the code
  "-w", # write back to the file

]

[formatter.haskell]
includes = ["*.hs"]
command = "hindent"
